
const COLLECTION_AUTHORIZATIONS = 'authorizations';
const COLLECTION_USERS = 'users';
const COLLECTION_REQUEST_QUERIES = 'request_queries';

module.exports = {
    COLLECTION_AUTHORIZATIONS,
    COLLECTION_USERS,
    COLLECTION_REQUEST_QUERIES
};